name: resume_crafter
description: Resume Crafter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  auto_route_generator: ^7.3.1
  bloc: ^8.1.2
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.2.0
  injectable_generator: ^2.3.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
